language: python
sudo: false
cache:
  directories:
    - ~/.cache/pip

env:
  matrix:
    - RASTERIO_VERSION=0.36.0
    - RASTERIO_VERSION=1.0.0a12
  global:
    - PIP_WHEEL_DIR=$HOME/.cache/pip/wheels
    - PIP_FIND_LINKS=file://$HOME/.cache/pip/wheels

python:
  - "2.7"
  - "3.5"
  - "3.6"
# - "nightly"

script: pytest --cov niche_vlaanderen --cov-report term-missing --verbose --tb=long

before_install:
  - export CPPFLAGS=`gdal-config --cflags`
  - export LDFLAGS=`gdal-config --libs`
  - export PROJ_LIB=/usr/share/proj

install:
  - pip install --use-wheel -r dev-requirements.txt rasterio==RASTERIO_VERSION
  - pip install sphinx_rtd_theme coveralls
  - pip install .

addons:
  apt:
    sources:
    - sourceline: 'ppa:ubuntugis/ubuntugis-unstable'
    packages:
    - libgdal-dev
    - gdal-bin
    - pandoc  # for generating documentation from jupyter notebook

after_success:
- coveralls || echo "coveralls failure"

before_deploy:
  - sphinx-build docs -a doc/_build/html

deploy:
    - user: stvhoey
      distributions: sdist bdist_wheel
      provider: pypi
      true:
        python: 3.5
        repo: inbo/niche_vlaanderen
        tags: true
      password:
        secure: !!binary |
          YzhwN3MxRnp2M1N1QjlxYXlUdU9VREdhUW9RRFlZTWIwUE94ejhKOW0wdVdJUFZCWHNIbmcyQkl3
          NFI4WUNFQmREUGZHMWF3REdhYzlMNWwzMHM5NzYyWjFLTndBRWl0b1ZlY1ZmVG1xL3AvYTVYQnM5
          L0d5MjAra0JKeFRJK3ZoQTl5b0Qrc0xiWXI1dEQvNnJWL2UvQXNGWitpZVNKSFdhYkhxcDI1Q0sy
          RTFld0djK3ZHL0U5emxxdWFQSWs5MnFjTUxZaFBVM0hFaU9RN1grWHc0Mzc0ZHBGU3NnaUxtQVJk
          emsra2lnaXloTzl2V296TXBLMTM2MXBjaXgxVTA4d1BvaENMRzBOZmFVRW1Fb3JESzBnRFBvSXpU
          UGRQckFFUlhtR3lOZnp1Yk1XMVdFUmZod1hQc2dSQkh2RmFyazNYUTJ6SjZTYjI1UVF0OGtPZ2RM
          MjZNNUtrbTd2ZTlMbk1mK3FadHExclVoYk9QZ3BqeE82QWk0Q2JmZnV1ejN5aFYvam9OUlQ1SmQr
          eElFWUQ2bElwUG9jK2svYWJEYktpZ2EvbWJxaUlhR2NhT2JTQmhzYjl1RC9zYmRKb1YydnI4YXh2
          RGZLcDlGcHBxM29NQm9FazN6TlNFaHkzY0ZMOFlsOURXTmRIQkt1YnVBVFM0eGxJSVAxSGl3ajRz
          bm0wRVFLNGRZekdFcXJHaG1wa0docG5GRUxDc0NsQW51ZStEYng4WjFOZDZDTW9TaEFadXV5OGho
          WlJBSFIyS29vbUduOGt2cFovSXJkb0g3MkJQVUdMenFzd0U2cVVBZytXd050TWY1dG0yMXNJUTZG
          MW9sYWUrRTNSUElVS3ZwemR4UHBIdkZUaHluNjg2WnNPc2NndWRYajRkR2dZQVlnRjJVSW5XMzA9
    - provider: pages
      skip_cleanup: true
      github_token: $GH_TOKEN
      local_dir: doc/_build/html
      on:
        branch: master
        python: 3.5
